import type { Metadata } from "next";
import { roboto } from "@/styles/fonts";
import "@/styles/globals.css";
import { UserProvider } from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
